openapi: 3.0.0
info:
  title: STD23006 - TD1
  version: 1.0.0
servers:
  - url: https://localhost.STD23006.com
paths:
  /customers:
    get:
      responses:
        '200':
          description: Liste des clients
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components"
components:
  schemas:
    Customer:
      type: object
      properties:
        name:
          type: string
        age:
          type: integer